import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { launch } from "./cdp.mjs";
const here = dirname(fileURLToPath(import.meta.url)).split(String.fromCharCode(92)).join("/");
const variant = process.argv[2] ?? "after";
const browser = await launch({ extPath: `${here}/ext-${variant}`.split("/").join(String.fromCharCode(92)), port: 9870 + Math.floor(Math.random() * 20), profileRoot: here });
const pg = await browser.newPage();
await pg.send("Page.bringToFront");
await pg.goto("https://www.linkedin.com/legal/privacy-policy", 2500);
const state = (label) => pg.eval(`(() => { const items = [document.querySelector(".language-selector__link--selected")]; const act = document.activeElement;
  const b0 = items[0]; const extra = " hasFocus=" + document.hasFocus() + " fw=" + b0.matches(":focus-within") + " cls=[" + b0.className.replace(/s+/g," ").trim() + "]"; return ${JSON.stringify(label)} + extra + " | active=" + (act && (act.className || act.tagName).toString().slice(-50)) + " || " + items.map((b) => { const cs = getComputedStyle(b); const s = b.querySelector("strong, span") || b; return (b.textContent.trim().slice(0, 16)) + " focus=" + b.matches(":focus") + " hover=" + b.matches(":hover") + " fv=" + b.matches(":focus-visible") + " bg=" + cs.backgroundColor + " ink=" + getComputedStyle(s).color; }).join(" ;; "); })()`);
console.log(await state("closed"));
await pg.eval(`(() => { document.querySelector(".language-selector__button").click(); return true; })()`);
await new Promise((r) => setTimeout(r, 500));
console.log(await state("opened by click"));
await pg.send("Input.dispatchKeyEvent", { type: "keyDown", key: "ArrowDown", code: "ArrowDown", windowsVirtualKeyCode: 40 });
await pg.send("Input.dispatchKeyEvent", { type: "keyUp", key: "ArrowDown", code: "ArrowDown", windowsVirtualKeyCode: 40 });
await new Promise((r) => setTimeout(r, 300));
console.log(await state("after ArrowDown"));
const box = await pg.eval(`(() => { const b = document.querySelectorAll(".language-selector__link")[2]; const r = b.getBoundingClientRect(); return { x: r.left + r.width / 2, y: r.top + r.height / 2 }; })()`);
await pg.send("Input.dispatchMouseEvent", { type: "mouseMoved", x: box.x, y: box.y });
await new Promise((r) => setTimeout(r, 300));
console.log(await state("hovering item 3"));
await browser.close();
