import { writeFileSync, readFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { launch } from "./cdp.mjs";
const here = dirname(fileURLToPath(import.meta.url)).split(String.fromCharCode(92)).join("/");
const variant = process.argv[2] ?? "after";
const browser = await launch({ extPath: `${here}/ext-${variant}`.split("/").join(String.fromCharCode(92)), port: 9530 + Math.floor(Math.random() * 20), profileRoot: here });
const pg = await browser.newPage();
await pg.send("Page.bringToFront");
await pg.goto("https://www.linkedin.com/help/linkedin/answer/a519904", 3000);
const svg = await pg.eval(`(() => { const l = document.querySelector('.global-footer li-icon[type="linkedin-logo"]'); return l.innerHTML.replace(/ d="[^"]*"/g, ' d=…').replace(/\s+/g, " "); })()`);
writeFileSync(`${here}/out-${variant}/logo-svg.txt`, svg);
console.log(svg.slice(0, 1600));
const info = await pg.eval(`(() => { const l = document.querySelector('.global-footer li-icon[type="linkedin-logo"]'); const vis = [...l.querySelectorAll("g")].filter((g) => getComputedStyle(g).display !== "none").map((g) => g.getAttribute("class")); return { visibleGroups: vis, parts: [...l.querySelectorAll("path, rect, polygon")].filter((p) => p.getBoundingClientRect().width > 0).map((p) => p.tagName + "." + (p.getAttribute("class") || "") + " parent=" + p.parentElement.getAttribute("class") + " fill=" + getComputedStyle(p).fill) }; })()`);
console.log(JSON.stringify(info, null, 1));
const r = await pg.eval(`(() => { const l = document.querySelector('.global-footer li-icon[type="linkedin-logo"]'); l.scrollIntoView(); const b = l.getBoundingClientRect(); return { x: b.left + scrollX - 40, y: b.top + scrollY - 10, width: b.width + 160, height: b.height + 20 }; })()`);
const s = await pg.send("Page.captureScreenshot", { format: "png", clip: { ...r, scale: 4 } });
writeFileSync(`${here}/out-${variant}/logo-zoom.png`, Buffer.from(s.data, "base64"));
await browser.close();
