import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { writeFileSync } from "node:fs";
import { launch } from "./cdp.mjs";
const here = dirname(fileURLToPath(import.meta.url)).split(String.fromCharCode(92)).join("/");
const browser = await launch({ extPath: `${here}/ext-after`.split("/").join(String.fromCharCode(92)), port: 9960 + Math.floor(Math.random() * 20), profileRoot: here });
const pg = await browser.newPage();
await pg.send("Emulation.setDeviceMetricsOverride", { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
await pg.send("Page.bringToFront");
await pg.goto("https://www.linkedin.com/legal/privacy-policy", 2500);
const q = () => pg.eval(`(() => { const n = document.querySelector(".custom-header__nav--mobile"); const cs = n && getComputedStyle(n); const r = n && n.getBoundingClientRect();
  const btns = [...document.querySelectorAll(".header__expand-nav-button")].map((b) => b.className + " visible=" + (b.getBoundingClientRect().width > 0));
  const icon = [...document.querySelectorAll(".header__expand-nav-button li-icon")].find((i) => i.getBoundingClientRect().width > 0); const hdr = document.querySelector(".page-header"); const iconInfo = icon && { color: getComputedStyle(icon).color, headerBg: getComputedStyle(hdr).backgroundColor };
  const items = n ? [...n.querySelectorAll("button, a")].filter((e) => e.getBoundingClientRect().width > 0).slice(0, 4).map((e) => e.textContent.trim().slice(0, 20) + " color=" + getComputedStyle(e).color) : [];
  return { iconInfo, navClass: n && n.className, visibility: cs && cs.visibility, bg: cs && cs.backgroundColor, h: r && Math.round(r.height), btns, items }; })()`);
console.log("before click", JSON.stringify(await q()));
await pg.eval(`(() => { const b = [...document.querySelectorAll(".header__expand-nav-button")].find((x) => x.getBoundingClientRect().width > 0); if (b) b.click(); return !!b; })()`);
await new Promise((r) => setTimeout(r, 700));
console.log("after click", JSON.stringify(await q()));
const r = await pg.send("Page.captureScreenshot", { format: "jpeg", quality: 60 });
writeFileSync(`${here}/out-after/mobile-nav.jpg`, Buffer.from(r.data, "base64"));
await browser.close();
