import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { launch } from "./cdp.mjs";
const here = dirname(fileURLToPath(import.meta.url)).split(String.fromCharCode(92)).join("/");
const variant = process.argv[2] ?? "after";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await launch({ extPath: `${here}/ext-${variant}`.split("/").join(String.fromCharCode(92)), port: 9480 + Math.floor(Math.random() * 30), profileRoot: here });
const popup = await browser.newPage();
await popup.goto(`chrome-extension://${browser.extId}/popup/popup.html`, 300);
const setMode = async (m) => { await popup.eval(`chrome.storage.local.set({ mode: ${JSON.stringify(m)} }).then(() => true)`); await sleep(400); };
const pg = await browser.newPage();
await pg.send("Page.bringToFront");
await pg.goto("https://www.linkedin.com/login", 2500);
const st = () => pg.eval(`document.body.getAttribute("data-color-scheme") + " dmli=" + document.documentElement.getAttribute("data-dmli")`);
const churn = () => pg.eval(`(async () => { let n = 0; const mo = new MutationObserver((r) => { for (const x of r) if (x.target === document.body || x.target === document.documentElement) n++; }); mo.observe(document.documentElement, { attributes: true }); mo.observe(document.body, { attributes: true, attributeFilter: ["class", "data-color-scheme"] }); await new Promise((r) => setTimeout(r, 2000)); mo.disconnect(); return n; })()`);
console.log("on:", await st(), "| churn", await churn());
await setMode("off"); await pg.send("Page.bringToFront"); console.log("off:", await st(), "| churn", await churn());
await setMode("on"); await pg.send("Page.bringToFront"); console.log("on again:", await st());
await pg.eval(`(() => { document.body.setAttribute("data-color-scheme", "light"); return true; })()`); await sleep(300);
console.log("after LinkedIn reset:", await st(), "| churn", await churn());
await browser.close();
